### PR TITLE
fix complie error(一部)

### PR DESCRIPTION
**Pull request by yumetodo**
```
decode_tree.cpp: In member function 'void decode_tree_node::decode(double)':
decode_tree.cpp:67:9: warning: variable 'minPatternRatio' set but not used [-Wunused-but-set-variable]
  double minPatternRatio = 1.0;
         ^
decode_tree.cpp:192:9: warning: variable 'minTableRatio' set but not used [-Wunused-but-set-variable]
  double minTableRatio = 1.0;
         ^
undef.cpp: In function 'bool compute_undef(std::vector<entry_t>&)':
undef.cpp:65:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
y.tab.c: In function 'int yyparse()':
y.tab.c:1343:24: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
parse_idef.y:27:6: note:   initializing argument 1 of 'void yyerror(char*)'
 void yyerror(char *);
      ^
y.tab.c:1460:35: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
```

### CODE REVIEW

**Comment by 173210** [comment]
Rejected:
Including unrelated changes. Please make a commit for each change. Also add your name to AUTHORS. Thanks.

**Comment by yumetodo** [comment]
> Please make a commit for each change

OK.

> Also add your name to AUTHORS.

What does it mean?

**Comment by 173210** [comment]
@yumetodo In free software development, contributors should leave their names or declare you donate your code to someone (i.e. give your copyright to him).

**Comment by yumetodo** [comment]
@173210 

> contributors should leave their names or declare you donate your code to someone 

What is a most popular way to leave my name or declare to donate?

**Comment by 173210** [comment]
@yumetodo Write your name to `AUTHORS`. It's at the root directory.

**Pull request closed without merging**
